### ISSUE TITLE
Settings option does not work

### ISSUE THREAD

**Issue by neupanedipen** [Mercandj/browser#1]
#### Expected behavior<br>
I should be able to access the app settings on clicking the Settings option.<br>
#### Actual behavior<br>
But the Settings option is inaccessible.<br>
#### How to reproduce<br>
1. Install the app from playstore.<br>
2. Launch the app.<br>
3. Click on three vertical dots from top right corner of the app and click on Settings. But it shows &quot;Not yet&quot; on clicking the option.<br>
* App Version: 1.00.02.20170102<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/dV5k_sbO_WU

**Comment by Mercandj** [comment]
Hi,
Thank a lot @neupanedipen for testing this minimalist app.
Indeed this app is very very minimalist (developed during one week-end) and I never took the time to implement the settings of this app. (only a small toast message to indicate that I should -> shame on me)
I will try to implement that soon.
Thks for the video =)

**Comment by neupanedipen** [comment]
That would be great. Seems like a great lightweight browser for me.

**Comment by Mercandj** [comment]
Hi, done in the version 1.00.08 [here](https://github.com/Mercandj/browser/releases/tag/1.00.08)

![browser-settings-1-00-08](https://user-images.githubusercontent.com/3717316/44119130-9e23640a-a018-11e8-80f4-5bca03e94a46.png)

I will close this issue.

Thks a lot @neupanedipen =)
